#!/usr/bin/env bash
#print numbers from 1-20.

x=1
while [ $x -le 20 ]
do
echo "$x";
case $x in
     echo "bad luck from China";
     echo "bad luck from Japan";
     echo "bad luck from Italy";
esac
    x=$(( x + 1 ))
done
